services:
  database:
    image: postgres:18
    container_name: home-finances-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234

  webapi:
    image: home-finances-webapi:latest
    container_name: home-finances-webapi
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__PgSQlConnectionString: Host=database;Port=5432;Database=home_finances_db;Username=postgres;Password=1234;
    depends_on:
      - database

  frontend:
    image: home-finances-frontend:latest
    container_name: home-finances-frontend
    ports:
      - 4000:4000
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - webapi
